apiVersion: v1
kind: Pod
metadata:
  name: zipkin-dashboard-monitoring-ms
  labels:
    app: zipkin
spec:
  containers:
  - name : zipkin
    image: openzipkin/zipkin:latest
    ports: 
      - containerPort: 9411